version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - rm -rf node_modules package-lock.json
      - echo Installing dependencies....
      - npm cache clean --force
      - npm install --include=dev
      - npm install -g @nestjs/cli

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Starting the application...
      - npm run start:prod

artifacts:
  files:
    - dist/**     
    - package.json 
    - .env          
  discard-paths: no

env:
  variables:
    NODE_ENV: "production"
