version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.16.0
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running lint checks...
      - npm run lint

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Build phase complete.

artifacts:
  files:
    - dist/**     
    - package.json 
    - .env          
  discard-paths: no

env:
  variables:
    NODE_ENV: "production" 
